### ISSUE TITLE
create email lists and email text for A/B testing of distiller services link

### ISSUE THREAD

**Issue by RoughIndustries** [RoughIndustries/com.roughindustries.cocktails_go#109]
We need to create 2 email lists of about 100 distillers.  We need to create the text for the 2 email lists where each set gets a link to a different page (i.e. the A/B part) and we track where they go and what they do.  We should modify the services page by some meaningful metric i.e. just brand awareness and remove the site hosting.  Maybe just have the list of service and an email address versus all the questions and an email address or maybe a link to a form.

**Comment by RoughIndustries** [comment]
we sent an AB test out to just 2 distillers with MailChimp.  MailChimp has a lot of issues with it and might be overkill for what we are looking for.  Neither distiller opened the email we sent.  We don't know if they saw it and ignored it or if it just went straight to spam.  We are going to follow up with using the contact pages provided on the websites.

**Comment by haddly** [comment]
need here a quote from "Crossing the Chasm" about how email marketing as an unknown startup does not work; direct contact (in person...). For paper
